version: '3'
services:
    web:
        image: webdevops/php-apache-dev:latest
        container_name: web
        restart: always
        user: application
        environment:
            - WEB_ALIAS_DOMAIN=local.domain.com:6080
            - WEB_DOCUMENT_ROOT=/app/pub
            - PHP_DATE_TIMEZONE=GST
            - PHP_DISPLAY_ERRORS=1
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=500M
            - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
            - ./src:/app:consistent
        ports:
            - "6080:80"
            - "6443:443"
            - "32823:22"
        links:
            - mysql
    mysql:
        image: mariadb:10
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=magento
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "5080:80"
        links:
            - mysql:db
        depends_on:
            - mysql

volumes:
    db-data:
        external: false
